<a href="https://colab.research.google.com/github/klauss1977/ML/blob/main/determinants-exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch
import tensorflow

# Determinantul unei matrici

Determinantul unei matrici mapeaza o patrice patrata la un scalar.
Permite stabilirea faptului ca o matrice poate fi inversata.
Pentru matricea **X**, determinantul se noteaza *det(X)*.                         
Daca *det(X)=0*, matricea **X** nu poate fi inversata.
Daca *det(X)=0*, matricea **X** este **singulara**, adica contine coloane care sunt dependente una de cealalta.

##Determinantul unei matrici 2x2

Definirea si afisarea matricii X in numpy

In [2]:
X=np.array([[4,2],[-5,-3]])
X

array([[ 4,  2],
       [-5, -3]])

Calcularea det(X)

In [3]:
np.linalg.det(X)

-2.0000000000000013

Definirea unei matrici singulare in numpy

In [4]:
N=np.array([[-4,1],[-8,2]])
N

array([[-4,  1],
       [-8,  2]])

Calculare det(N)

In [5]:
np.linalg.det(N)

0.0

Matricea N este singulara, det(N)=0.  
Incercarea de aflare inversa lui N va determina eroare de matrice singulara.

In [6]:
Ninv=np.linalg.inv(N)

LinAlgError: ignored

##Generalizarea determinantilor. Calculul determinantilor matricilor mai mari decat 2x2

Definire matrice X3 de dimensiune 3x3 in pytorch

In [7]:
X3=np.array([[1,2,4],[2,-1,3],[0,5,1]])
X3

array([[ 1,  2,  4],
       [ 2, -1,  3],
       [ 0,  5,  1]])

Calculare det(X3)

In [8]:
np.linalg.det(X3)

19.999999999999996