<a href="https://colab.research.google.com/github/klauss1977/ML/blob/main/exercitiu_eigenvectors_3d.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Exercises**:

1. Use PyTorch to confirm $Xv = \lambda v$ for the first eigenvector of $X$.
2. Confirm $Xv = \lambda v$ for the remaining eigenvectors of $X$ (you can use NumPy or PyTorch, whichever you prefer).

# New Section

In [ ]:
import numpy as np
import torch

Definire si afisare matrice X in Py Torch. Atentie, trebuie sa fie float!!!

In [ ]:
X=torch.tensor([[25,2,9],[5,26,-5],[3,7,-1.]])
X

tensor([[25.,  2.,  9.],
        [ 5., 26., -5.],
        [ 3.,  7., -1.]])

Aflare eigenvectori si eigenvalues pentru matricea X definita mai sus.
Se foloseste metoda torch.linalg.eig() care va avea ca rezultat o pereche vector de eigenvalues si matrice de eigenvectori. Componentele vectorului de eigenvalues si matricii de eigenvectori sunt numere complexe.

In [ ]:
eigens = torch.linalg.eig(X)

Afisare pereche eigens

In [ ]:
eigens

torch.return_types.linalg_eig(
eigenvalues=tensor([29.6762+0.j, 20.6212+0.j, -0.2974+0.j]),
eigenvectors=tensor([[ 0.7118+0.j,  0.6502+0.j, -0.3422+0.j],
        [ 0.6665+0.j, -0.7446+0.j,  0.2379+0.j],
        [ 0.2217+0.j, -0.1509+0.j,  0.9090+0.j]]))

Extragere eigenvalue_1 si transformare in tip float

In [ ]:
eigenvalue_1=eigens.eigenvalues[0].float()
eigenvalue_1

tensor(29.6762)

Extragere eigenvalue_2 si transformare in tip float

In [ ]:
eigenvalue_2=eigens.eigenvalues[1].float()
eigenvalue_2

tensor(20.6212)

Extragere eigenvalue_3 si transformare in tip float

In [ ]:
eigenvalue_3=eigens.eigenvalues[2].float()
eigenvalue_3

tensor(-0.2974)

Extragere eigenvector_1 si transformare in tip float

In [ ]:
eigenvector_1=eigens.eigenvectors[:,0].float()
eigenvector_1

tensor([0.7118, 0.6665, 0.2217])

Extragere eigenvector_2 si transformare in tip float

In [ ]:
eigenvector_2=eigens.eigenvectors[:,1].float()
eigenvector_2

tensor([ 0.6502, -0.7446, -0.1509])

Extragere eigenvector_3 si transformare in tip float

In [ ]:
eigenvector_3=eigens.eigenvectors[:,2].float()
eigenvector_3

tensor([-0.3422,  0.2379,  0.9090])

Inmultire matrice X cu eigenvector_1

In [ ]:
Xv_1=torch.matmul(X,eigenvector_1)
Xv_1

tensor([21.1223, 19.7798,  6.5792])

Inmultire eigenvalue_1 cu eigenvector_1.
Se verifica egalitatea X *x* eigenvector_1==eigenvalue_1 *x* eigenvector_1

In [ ]:
eigenvalue_1*eigenvector_1

tensor([21.1223, 19.7798,  6.5792])

Inmultire matrice X cu eigenvector_2

In [ ]:
Xv_2=torch.matmul(X,eigenvector_2)
Xv_2

tensor([ 13.4077, -15.3554,  -3.1110])

Inmultire eigenvalue_2 cu eigenvector_2.
Se verifica egalitatea X *x* eigenvector_2==eigenvalue_2 *x* eigenvector_2

In [ ]:
eigenvalue_2*eigenvector_2

tensor([ 13.4077, -15.3554,  -3.1110])

Inmultire matrice X cu eigenvector_3

In [ ]:
Xv_3=torch.matmul(X,eigenvector_3)
Xv_3

tensor([ 0.1018, -0.0708, -0.2703])

Inmultire eigenvalue_3 cu eigenvector_3.
Se verifica egalitatea X *x* eigenvector_3==eigenvalue_3 *x* eigenvector_3

In [ ]:
eigenvalue_3*eigenvector_3

tensor([ 0.1018, -0.0708, -0.2703])

Aplicare metoda eig() in numpy

In [ ]:
eigens_num=np.linalg.eig(X)
eigens_num

(array([29.676231  , 20.621174  , -0.29740566], dtype=float32),
 array([[-0.71175736, -0.6501921 , -0.34220475],
        [-0.66652125,  0.7446406 ,  0.23789717],
        [-0.22170001,  0.15086636,  0.9090109 ]], dtype=float32))